#ifndef mainHPP
#define mainHPP
#include <ExtCtrls.hpp>
#include <Buttons.hpp>
#include <StdCtrls.hpp>
#include <dxBarExtItems.hpp>
#include <dxBar.hpp>
#include <Dialogs.hpp>
#include <Forms.hpp>
#include <Controls.hpp>
#include <Graphics.hpp>
#include <Classes.hpp>
#include <SysUtils.hpp>
#include <Messages.hpp>
#include <Windows.hpp>
#include <SysInit.hpp>
#include <System.hpp>
#include <ActnList.hpp>
#include <ComCtrls.hpp>
#include <ImgList.hpp>
#include "EBarsUtils.h"
//-- ------------------------------------------------------
class TEBar2000DemoMainForm : public TForm
{
__published:
  TPanel *Panel1;
  TScrollBox *ScrollBox1;
  TGroupBox *gbOptions;
  TRadioGroup *rgMenuAnimations;
  TGroupBox *bgBar1;
  TSpeedButton *SpeedButton1;
  TCheckBox *cbAllowCustomizingBar1;
  TCheckBox *cbAllowQuickCustomizingBar1;
  TCheckBox *cbAllowResetBar1;
  TCheckBox *CheckBox1;
  TGroupBox *gbBar2;
  TSpeedButton *SpeedButton2;
  TCheckBox *cbAllowCustomizingBar2;
  TCheckBox *cbAllowQuickCustomizingBar2;
  TCheckBox *cbAllowResetBar2;
  TCheckBox *CheckBox2;
  TGroupBox *rgBar3;
  TCheckBox *cbRotateWhenVertical;
  TRadioGroup *rgStyle;
  TGroupBox *gbImages;
  TCheckBox *cbHotImages;
  TCheckBox *cbDisabledImages;
  TCheckBox *CheckBox4;
  TGroupBox *gbMiscellaneous;
  TSpeedButton *sbFont;
  TSpeedButton *sbDockColor;
  TCheckBox *cbCanCustomize;
  TCheckBox *cbAllowReset;
  TCheckBox *cbShowHelpButton;
  TCheckBox *cbSunkenBorder;
  TCheckBox *cbMenusShowRecentItemsFirst;
  TCheckBox *cbShowFullMenusAfterDelay;
  TCheckBox *cbStretchGlyphs;
  TCheckBox *cbShowCaptions;
  TGroupBox *gbAlphaBlending;
  TLabel *Label2;
  TLabel *Label3;
  TLabel *Label5;
  TTrackBar *tbStandard;
  TGroupBox *GroupBox1;
  TLabel *Label1;
  TLabel *Label4;
  TLabel *Label6;
  TTrackBar *tbFormatting;
  TdxBarManager *dxBarManager;
  TdxBarSubItem *siFile;
  TdxBarSubItem *siEdit;
  TdxBarSubItem *siView;
  TdxBarSubItem *siInsert;
  TdxBarSubItem *siFormat;
  TdxBarSubItem *siTools;
  TdxBarSubItem *siTable;
  TdxBarSubItem *siWindow;
  TdxBarSubItem *siHelp;
  TdxBarLargeButton *btnNew;
  TdxBarLargeButton *btnNewWebPage;
  TdxBarLargeButton *btnNewEmailMessage;
  TdxBarLargeButton *btnNewBlankDocument;
  TdxBarLargeButton *btnOpen;
  TdxBarLargeButton *btnClose;
  TdxBarLargeButton *btnCloseAll;
  TdxBarLargeButton *btnSave;
  TdxBarLargeButton *btnSaveAs;
  TdxBarLargeButton *btnSaveAsWebPage;
  TdxBarLargeButton *btnSaveAll;
  TdxBarLargeButton *btnSaveVersion;
  TdxBarLargeButton *btnWebPagePreview;
  TdxBarLargeButton *btnPageSetup;
  TdxBarLargeButton *btnPrintPreview;
  TdxBarLargeButton *btnPrint;
  TdxBarLargeButton *btnPrintSetup;
  TdxBarLargeButton *btnMailRecipient;
  TdxBarLargeButton *btnSendNow;
  TdxBarLargeButton *btnRoundRecipient;
  TdxBarLargeButton *btnExchengeFolder;
  TdxBarLargeButton *btnFaxRecipient;
  TdxBarLargeButton *btnSendToMicrosoftPowerPoint;
  TdxBarLargeButton *btnVersion;
  TdxBarLargeButton *btnProperties;
  TdxBarLargeButton *btnExit;
  TdxBarLargeButton *btnUndo;
  TdxBarLargeButton *btnRedo;
  TdxBarLargeButton *btnRepeat;
  TdxBarLargeButton *btnCut;
  TdxBarLargeButton *btnCopy;
  TdxBarLargeButton *btnPaste;
  TdxBarLargeButton *btnPasteTable;
  TdxBarLargeButton *btnPasteSpecial;
  TdxBarLargeButton *btnPasetAsHyperlink;
  TdxBarLargeButton *btnClear;
  TdxBarLargeButton *dxBarButton1;
  TdxBarLargeButton *btnFind;
  TdxBarLargeButton *btnFindNext;
  TdxBarLargeButton *btnReplace;
  TdxBarLargeButton *btnGoTo;
  TdxBarLargeButton *btnLinks;
  TdxBarLargeButton *btnObject;
  TdxBarLargeButton *btnPicture;
  TdxBarLargeButton *btnCreateTextBoxLink;
  TdxBarLargeButton *btnBreakForwardLink;
  TdxBarLargeButton *btnNextTextBox;
  TdxBarLargeButton *btnPreviousTextBox;
  TdxBarLargeButton *btnNextComment;
  TdxBarLargeButton *btnPreviousComment;
  TdxBarCombo *cbZoom;
  TdxBarLargeButton *btnRuler;
  TdxBarLargeButton *btnShowAll;
  TdxBarLargeButton *btnDocumentMap;
  TdxBarLargeButton *btnViewFieldCodes;
  TdxBarLargeButton *btnShowFieldShading;
  TdxBarLargeButton *btnFullScreen;
  TdxBarLargeButton *btnMagnifier;
  TdxBarLargeButton *btnZoom100;
  TdxBarLargeButton *btnFitToWindow;
  TdxBarLargeButton *btnOnePage;
  TdxBarLargeButton *btnNormal;
  TdxBarLargeButton *btnWebLayout;
  TdxBarLargeButton *btnPrintLayout;
  TdxBarLargeButton *btnOutLine;
  TdxBarSubItem *siToolBars;
  TdxBarLargeButton *btnComments;
  TdxBarLargeButton *btnHTMLSource;
  TdxBarLargeButton *dxBarButton2;
  TdxBarLargeButton *dxBarButton3;
  TdxBarLargeButton *btnPromote;
  TdxBarLargeButton *btnDemote;
  TdxBarLargeButton *btnDemoteToBodyText;
  TdxBarLargeButton *btnMoveUp;
  TdxBarLargeButton *btnMoveDown;
  TdxBarLargeButton *btnExpand;
  TdxBarLargeButton *btnCollapse;
  TdxBarLargeButton *btnAll;
  TdxBarLargeButton *btnShowHeading1;
  TdxBarLargeButton *btnShowHeading2;
  TdxBarLargeButton *btnShowHeading3;
  TdxBarLargeButton *btnShowHeading4;
  TdxBarLargeButton *btnShowHeading5;
  TdxBarLargeButton *btnFirstLineOnlyView;
  TdxBarLargeButton *btnShowFormatting;
  TdxBarLargeButton *btnMasterDocumentView;
  TdxBarLargeButton *btnNextHeader;
  TdxBarLargeButton *btnPreviousHeader1;
  TdxBarLargeButton *btnHideBodyText;
  TdxBarLargeButton *btnPageBreak;
  TdxBarLargeButton *btnInsertColumnBreak;
  TdxBarLargeButton *btnInsertSectionBreak;
  TdxBarLargeButton *btnPageNumber;
  TdxBarLargeButton *btnNumberOfPages;
  TdxBarLargeButton *btnDate;
  TdxBarLargeButton *btnTime;
  TdxBarLargeButton *btnPageNumbers;
  TdxBarLargeButton *btnDateAndTime;
  TdxBarLargeButton *btnAutoText;
  TdxBarLargeButton *btnSumbol;
  TdxBarLargeButton *btnComment;
  TdxBarLargeButton *btnDeleteComment;
  TdxBarLargeButton *btnFootnote;
  TdxBarLargeButton *InsertListNumField;
  TdxBarLargeButton *btnHyperlink;
  TdxBarLargeButton *btnFromFile;
  TdxBarLargeButton *btnTextBox;
  TdxBarLargeButton *btnHorizontal;
  TdxBarLargeButton *btnFile;
  TdxBarLargeButton *btnInsertExcelSpreadsheet;
  TdxBarLargeButton *btnChart;
  TdxBarLargeButton *btnWordArt;
  TdxBarLargeButton *btnEquationEditor;
  TdxBarLargeButton *btnVoiceComment;
  TdxBarLargeButton *btnPenComment;
  TdxBarLargeButton *btnFromScannerOrCamear;
  TdxBarLargeButton *btnClipArt;
  TdxBarLargeButton *btnDataBase;
  TdxBarLargeButton *btnAddressBook;
  TdxBarLargeButton *btnObject1;
  TdxBarFontNameCombo *cbFontName;
  TdxBarCombo *cnFontSize;
  TdxBarCombo *cbStyle;
  TdxBarLargeButton *btnBold;
  TdxBarLargeButton *btnItalic;
  TdxBarLargeButton *btnUnderline;
  TdxBarLargeButton *btnFormatPainter;
  TdxBarLargeButton *btnFontColor;
  TdxBarLargeButton *btnHighlight;
  TdxBarLargeButton *btnGrowFont;
  TdxBarLargeButton *btnShrinkFont;
  TdxBarLargeButton *btnGrowFont1Pt;
  TdxBarLargeButton *btnShinkFont1Pt;
  TdxBarLargeButton *btnSmallCaps;
  TdxBarLargeButton *btnAllCaps;
  TdxBarLargeButton *btnSuperscript;
  TdxBarLargeButton *btnsubscript;
  TdxBarLargeButton *btnDecreaseIndent;
  TdxBarLargeButton *btnIncreaseIndent;
  TdxBarLargeButton *btnNumbering;
  TdxBarLargeButton *btnBullets;
  TdxBarLargeButton *btnAlignLeft;
  TdxBarLargeButton *btnCenter;
  TdxBarLargeButton *btnAlignRight;
  TdxBarLargeButton *btnJustify;
  TdxBarLargeButton *btnColumns;
  TdxBarLargeButton *btnAutoFormat;
  TdxBarLargeButton *btnInsertListNumField;
  TdxBarLargeButton *btnChangeTextDirection;
  TdxBarLargeButton *btnFont;
  TdxBarLargeButton *btnParagraph;
  TdxBarLargeButton *btnBulletsAndNumbering1;
  TdxBarLargeButton *btnGropCap;
  TdxBarLargeButton *btnStyle;
  TdxBarLargeButton *btnTextDirection;
  TdxBarLargeButton *btnChangeCase;
  TdxBarLargeButton *btnTheme;
  TdxBarLargeButton *btnCOMAddIns;
  TdxBarLargeButton *btnSpellingandGrammar;
  TdxBarLargeButton *btnNextMisspelling;
  TdxBarLargeButton *btnHideSpellingErrors;
  TdxBarLargeButton *btnHideGrammarErrors;
  TdxBarLargeButton *btnSpelling;
  TdxBarLargeButton *btnDictionary;
  TdxBarLargeButton *btnGrammar;
  TdxBarLargeButton *btnSetLanguage;
  TdxBarLargeButton *btnThesaurus;
  TdxBarLargeButton *btnWordCount;
  TdxBarLargeButton *btnAutoSummarize;
  TdxBarLargeButton *btnResumarize;
  TdxBarLargeButton *btnHighlightShowOnlySummary;
  TdxBarLargeButton *btnAutoCorrect;
  TdxBarLargeButton *btnToolsAutoCorrectExceptions;
  TdxBarLargeButton *btnHighlightChanges;
  TdxBarLargeButton *btnTrackChanges;
  TdxBarLargeButton *btnAcceptOrRejectChanges;
  TdxBarLargeButton *btnAcceptChange;
  TdxBarLargeButton *btnRejectChange;
  TdxBarLargeButton *btnNextChange;
  TdxBarLargeButton *btnPreviousChange;
  TdxBarLargeButton *btnCompareDocuments;
  TdxBarLargeButton *btnMergeDocuments;
  TdxBarLargeButton *btnProtectDocument;
  TdxBarLargeButton *btnEnvelopesAndLabels;
  TdxBarLargeButton *btnLetterWizard;
  TdxBarLargeButton *btnMacros;
  TdxBarLargeButton *btnRecordMacroStopRecorder;
  TdxBarLargeButton *btnSecurity;
  TdxBarLargeButton *btnVisualBasicEditor;
  TdxBarLargeButton *btnMicrosoftScriptEditor;
  TdxBarLargeButton *btnInsertScript;
  TdxBarLargeButton *btnRemoveAllScripts;
  TdxBarLargeButton *btnShowAllScripts;
  TdxBarLargeButton *btnStopRecordind;
  TdxBarLargeButton *btnPauseRecording;
  TdxBarLargeButton *btnUpdateField;
  TdxBarLargeButton *btnRepaginate;
  TdxBarLargeButton *btnShrinkOnePage;
  TdxBarLargeButton *btnInsertTable;
  TdxBarLargeButton *dxBarButton4;
  TdxBarLargeButton *btnCells;
  TdxBarLargeButton *btnRows;
  TdxBarLargeButton *btnColumnsToTheLeft;
  TdxBarLargeButton *btnDeleteCells;
  TdxBarLargeButton *btnDeleteRows;
  TdxBarLargeButton *btnDeleteColumns;
  TdxBarLargeButton *btnGridLines;
  TdxBarLargeButton *btnTableAutoFormat;
  TdxBarLargeButton *btnAutoSum;
  TdxBarLargeButton *btnSortAscepring;
  TdxBarLargeButton *btnSortDescending;
  TdxBarLargeButton *btnFindInField;
  TdxBarSubItem *btnTableInsert;
  TdxBarLargeButton *btnTablesandBordersToolbar;
  TdxBarLargeButton *btnDrawTable;
  TdxBarLargeButton *btnEraser;
  TdxBarLargeButton *btnMergeCells;
  TdxBarLargeButton *btnAplitCells;
  TdxBarLargeButton *btnAlignTop;
  TdxBarLargeButton *btnCenterVerticaly;
  TdxBarLargeButton *btnAlignBottom;
  TdxBarSubItem *siCellAlignment;
  TdxBarLargeButton *btnDistributeRowsEvenly;
  TdxBarLargeButton *btnDistributeColumnsEvenly;
  TdxBarLargeButton *btnNewWindow;
  TdxBarLargeButton *btnArrangeAll;
  TdxBarLargeButton *btnSplit;
  TdxBarLargeButton *btnNextWindow;
  TdxBarLargeButton *btnPreviousWindow;
  TdxBarLargeButton *dxBarButton7;
  TdxBarLargeButton *dxBarButton8;
  TdxBarLargeButton *dxBarButton9;
  TdxBarLargeButton *dxBarButton10;
  TdxBarLargeButton *dxBarButton11;
  TdxBarLargeButton *dxBarButton12;
  TdxBarLargeButton *dxBarButton13;
  TdxBarLargeButton *dxBarButton14;
  TdxBarSubItem *siSendTo;
  TdxBarSubItem *siPicture;
  TdxBarSubItem *siLanguage;
  TdxBarLargeButton *btnCustomize;
  TdxBarSubItem *siMacro;
  TdxBarSubItem *siInsertTable;
  TdxBarSubItem *siDeleteTable;
  TdxBarSubItem *siAutoFit;
  TdxBarLargeButton *btnTableProperties;
  TdxBarLargeButton *btnFontColorItem;
  TdxBarLargeButton *btnDownFontColorItem;
  TdxBarLargeButton *btnCustomFontColor;
  TdxBarLargeButton *btnColorItem;
  TdxBarLargeButton *btnDownColorItem;
  TdxBarLargeButton *btnCustomColor;
  TdxBarLargeButton *btnStandard;
  TdxBarLargeButton *btnFormatting;
  TdxBarLargeButton *btnInternet;
  TdxBarCombo *cbAddress;
  TdxBarLargeButton *btnBack;
  TdxBarLargeButton *btnForward;
  TdxBarLargeButton *btnStop;
  TdxBarLargeButton *btnRefresh;
  TdxBarLargeButton *btnHome;
  TdxBarLargeButton *btnAttach;
  TdxBarLargeButton *dxBarButton5;
  TdxBarLargeButton *dxBarButton6;
  TdxBarLargeButton *dxBarButton15;
  TdxBarLargeButton *dxBarButton16;
  TdxBarLargeButton *dxBarButton17;
  TdxBarLargeButton *dxBarButton18;
  TdxBarLargeButton *dxBarButton19;
  TdxBarLargeButton *dxBarLargeButton1;
  TdxBarLargeButton *dxBarLargeButton2;
  TImageList *Images;
  TImageList *StyleImages;
  TdxBarPopupMenu *FontColorPopupMenu;
  TdxBarPopupMenu *HightlightColorPopupMenu;
  TColorDialog *ColorDialog;
  TFontDialog *FontDialog;
  TImageList *ilHotImages;
  TImageList *ilDisabledImages;
	void __fastcall cbStyleMeasureItem(TdxBarCustomCombo* Sender, int AIndex, int &AHeight);
	void __fastcall cbStyleDrawItem(TdxBarCustomCombo* Sender, int AIndex, TRect
		&ARect, TOwnerDrawState AState);
	void __fastcall FormCreate(TObject* Sender);
	void __fastcall btnFontColorItemClick(TObject* Sender);
	void __fastcall btnCustomFontColorClick(TObject* Sender);
	void __fastcall btnColorItemClick(TObject* Sender);
	void __fastcall btnCustomColorClick(TObject* Sender);
	void __fastcall btnStandardClick(TObject* Sender);
	void __fastcall sbFontClick(TObject* Sender);
	void __fastcall cbCanCustomizeClick(TObject* Sender);
	void __fastcall sbDockColorClick(TObject* Sender);
	void __fastcall cbAllowResetClick(TObject* Sender);
	void __fastcall cbShowHelpButtonClick(TObject* Sender);
	void __fastcall cbSunkenBorderClick(TObject* Sender);
	void __fastcall cbMenusShowRecentItemsFirstClick(TObject* Sender);
	void __fastcall rgMenuAnimationsClick(TObject* Sender);
	void __fastcall SpeedButton1Click(TObject* Sender);
	void __fastcall SpeedButton2Click(TObject* Sender);
	void __fastcall cbAllowCustomizingBar1Click(TObject* Sender);
	void __fastcall cbAllowQuickCustomizingBar1Click(TObject* Sender);
	void __fastcall cbAllowResetBar1Click(TObject* Sender);
	void __fastcall cbAllowCustomizingBar2Click(TObject* Sender);
	void __fastcall cbAllowQuickCustomizingBar2Click(TObject* Sender);
	void __fastcall cbAllowResetBar2Click(TObject* Sender);
	void __fastcall cbShowFullMenusAfterDelayClick(TObject* Sender);
	void __fastcall dxBarManagerHelpButtonClick(TObject* Sender);
	void __fastcall cbRotateWhenVerticalClick(TObject* Sender);
	void __fastcall btnCustomizeClick(TObject* Sender);
	void __fastcall dxBarManagerBarVisibleChange(TdxBarManager* Sender, TdxBar* ABar);
	void __fastcall cbStretchGlyphsClick(TObject* Sender);
	void __fastcall rgStyleClick(TObject* Sender);
	void __fastcall CheckBox1Click(TObject* Sender);
	void __fastcall CheckBox2Click(TObject* Sender);
  void __fastcall TrackBarChange(TObject *Sender);
  void __fastcall cbHotImagesClick(TObject *Sender);
  void __fastcall cbDisabledImagesClick(TObject *Sender);
  void __fastcall CheckBox4Click(TObject *Sender);
  void __fastcall cbShowCaptionsClick(TObject *Sender);

private:
	void __fastcall UpdateColorItems(TdxBarLargeButton *AButton, TdxBarLargeButton *ADownButton,
 TdxBarLargeButton *ACustomButton, TdxBarLargeButton *AItemButton, TdxBarPopupMenu *APopupMenu);

public:
    __fastcall TEBar2000DemoMainForm(TComponent* Owner);
	bool FUpdateVisible;
};

//-- var, const, procedure ---------------------------------------------------
extern PACKAGE TEBar2000DemoMainForm* EBar2000DemoMainForm;

//-- end unit ----------------------------------------------------------------
#endif	// main
