unit LocalizationStrs;

{$I cxVer.inc}

interface

uses
  dxCore;

resourcestring
  sActionsBarCaption = 'Actions';
  sAddressColumn = 'Address';
  sAddressLabel = 'ADDRESS';
  sAddressLine = 'Address Line';
  sAgendaOptions = 'Agenda Options';
  sAlignTextCenter = 'Center';
  sAlignTextCenterHintDescription = 'Center text.';
  sAlignTextLeft = 'Align text left';
  sAlignTextLeftHintDescription = 'Align text to the left.';
  sAlignTextRight = 'Align text right';
  sAlignTextRightDescription = 'Align text to the right.';
  sAscendingButton = 'Ascending';
  sAssignedEmployeesTab = 'Assigned Employees';
  sAssignedToColumn = 'Assigned To';
  sAssignedToLabel = 'ASSIGNED TO';
  sAutomation = 'Automation';
  sAvailableForSaleLabel = 'AVAILABLE FOR SALE';
  sBackorderColumn = 'Backorder';
  sBackOrdersLabel = 'BACKORDERS';
  sBarButtonCopyHint = 'Copy';
  sBarButtonCutHint = 'Cut';
  sBarButtonFindHint = 'Find';
  sBarButtonPasteHint = 'Paste';
  sBarButtonReplaceHint = 'Replace';
  sBarButtonSaveHint = 'Save';
  sBarButtonSelectAllHint = 'Select &All';
  sbbBusy = 'Busy';
  sbbFree = 'Free';
  sbBold = 'Bold';
  sbbOutOfOffice = 'Out Of Office';
  sbbTentative = 'Tentative';
  sbCalendarTimelines10Minutes = '10 Minutes';
  sbCalendarTimelines15Minutes = '15 Minutes';
  sbCalendarTimelines30Minutes = '30 Minutes';
  sbCalendarTimelines5Minutes = '5 Minutes';
  sbCalendarTimelines60Minutes = '60 Minutes';
  sbCalendarTimelines6Minutes = '6 Minutes';
  sbCalendarTimelinesDay = 'Day';
  sbCalendarTimelinesMonth = 'Month';
  sbCalendarTimelinesWeek = 'Week';
  sBillingAddressLabel = 'BILLING ADDRESS';
  sBirthDate = 'Birth Date';
  sbItalic = 'Italic';
  sBoldHintDescription = 'Change to a heavier font.';
  sBulletedList = 'Bulleted List';
  sbUnderline = 'Underline';
  sCancelButton = 'Cancel';
  sCategory = 'Category';
  sCategoryLabel = 'CATEGORY';
  scbReminder = 'Reminder:';
  sCityColumn = 'City';
  sCityLabel = 'CITY';
  sClear = 'Clear';
  sClipboard = 'Clipboard';
  sCloseButton = 'Close';
  sCompanyLabel = 'COMPANY';
  sComplete = 'Complete';
  sCompleteColumn = '% Complete';
  sCompleted = 'Completed';
  sCompleteLabel = '% COMPLETE';
  sContactEdit = 'Edit Contact';
  sContactNew = 'New Contact';
  sContactsColumn = 'Contacts';
  sContactViewAlphabetical = 'Alphabetical';
  sContactViewByState = 'By State';
  sContactViewCard = 'Card';
  sContactViewList = 'List';
  sCopyHintDescription = 'Copy the selection and put it on the Clipboard.';
  sCostColumn = 'Cost';
  sCostLabel = 'COST';
  sCreatedByColumn = 'Created By';
  sCreatedOnColumn = 'Created On';
  sCurrentInventoryLabel = 'CURRENT INVENTORY';
  sCurrentView = 'Current View';
  sCustomersLabel = 'CUSTOMERS';
  sCustomersSubMenuAllCustomersCaption = 'All Customers';
  sCustomersSubMenuJohnsAccountCaption = 'John''s Account';
  sCustomersSubMenuMyAccountCaption = 'My Account';
  sCustomersSubMenuTopStoresCaption = 'Top Stores';
  sCutHintDescription = 'Cut the selection from the document and put it on the Clipboard.';
  sDate = 'Date';
  sDateCompleted = 'Date Completed';
  sDateCreated = 'Date Created';
  sDeleteConfirmation = 'Do you want to delete this task?';
  sDeleteItemDescription = 'Delete current mail';
  sDepartmentColumn = 'Department';
  sDepartmentLabel = 'DEPARTMENT';
  sDescendingButton = 'Descending';
  sDescription = 'Description';
  sDescriptionLabel = 'DESCRIPTION';
  sDevelopment = 'Development';
  sDiscountColumn = 'Discount';
  sDOBLabel = 'DOB';
  sDr = 'Dr.';
  sDueDateColumn = 'Due Date';
  sDueDateLabel = 'DUE DATE';
  sdxBarButtonCopy = '&Copy';
  sdxBarButtonCut = 'Cu&t';
  sdxBarButtonFind = 'Find';
  sdxBarButtonPaste = '&Paste';
  sdxBarButtonPrint = '&Print';
  sdxBarButtonReplace = 'Replace';
  sdxBarButtonSave = 'Save';
  sdxBarButtonSelectAll = 'Select &All';
  sEditButton = 'Edit';
  sEditing = 'Editing';
  sEditTaskFormCaption = 'EDIT TASK';
  sEmail = 'Email';
  sEmailLabel = 'EMAIL';
  sEmployeeFilterCaption = 'EMPLOYEE Status';
  sEmployeeStatusCommission = 'Commission';
  sEmployeeStatusContract = 'Contract';
  sEmployeeStatusOnLeave = 'On Leave';
  sEmployeeStatusSalaried = 'Salaried';
  sEmployeeStatusTerminated = 'Terminated';
  sExit = 'Exit';
  sExport = 'Export';
  sFamily = 'Family';
  sFaxColumn = 'Fax';
  sFaxLabel = 'FAX';
  sFilterAllCaption = 'All';
  sFilterTaskCaption = ' TASKS';
  sFindHintDescription = 'Find text in the document.';
  sFirstName = 'First Name';
  sFirstNameLabel = 'FIRST NAME';
  sFlagStatus = 'Flag Status';
  sFlip = 'Flip';
  sFollowCustom = 'Custom';
  sFollowNextWeek = 'Next Week';
  sFollowNoDate = 'No Date';
  sFollowThisWeek = 'This Week';
  sFollowTomorrow = 'Tomorrow';
  sFollowUp = 'Follow Up';
  sFontColor = 'Font color';
  sForwardDescription = 'Forward current mail to someone else';
  sFrameBar1BarCaption = 'Appointment';
  sFrameBar2BarCaption = 'Navigate';
  sFrameBar3BarCaption = 'Arrange';
  sFrameBar4BarCaption = 'Group By';
  sFrameBar5BarCaption = 'Layout';
  sFrom = 'From';
  sFullNameColumn = 'Full Name';
  sFullNameLabel = 'FULL NAME';
  sGrandTotalLabel = 'GRAND TOTAL';
  sHighlighting = 'Highlighting';
  sHireDateLabel = 'HIRE DATE';
  sHomePhoneLabel = 'HOME PHONE';
  sHomeTabCaption = 'HOME';
  sHTMLFile = 'HTML File';
  sHTMLFileDescription = 'Web Page';
  sImportance = 'Importance';
  sInfo = 'Info';
  sInventoryColumn = 'Inventory';
  sInvoiceColumn = 'Invoice';
  sItalicHintDescription = 'Change to an italic font.';
  sItemCountInfo = 'Items: %d';
  sLanguageSubMenuArabicCaption = 'Arabic';
  sLanguageSubMenuEnglishCaption = 'English';
  sLanguageSubMenuHebrewCaption = 'Hebrew';
  sLanguageSubMenuLTRCaption = 'LEFT TO RIGHT';
  sLanguageSubMenuRTLCaption = 'RIGHT TO LEFT';
  sLastName = 'Last Name';
  sLastNameLabel = 'LAST NAME';
  sLayout = 'Layout';
  slbCalendarGoToDay = 'Go to &Today';
  slbCalendarGroupByDate = '&Group by Date';
  slbCalendarGroupByResource = '&Group by Resource';
  slbCalendarLayoutCompressWeekend = 'Compress Weekend';
  slbCalendarNavigateNext = 'Forward';
  slbCalendarNavigatePrior = 'Backward';
  slbCalendarNewRepeatingEvent = 'New Recurring &Appointment';
  slbCalendarNoGroup = '&Group by None';
  slbCalendarViewAgenda = '&Agenda View';
  slbCalendarViewDay = '&Day View';
  slbCalendarViewDayTimelines = '&Time Scales';
  slbCalendarViewMonth = '&Month View';
  slbCalendarViewTimeline = '&Timeline View';
  slbCalendarViewWeek = '&Week View';
  slbCalendarViewWorkWeek = 'Wo&rk Week View';
  slbCalendarWorktime = 'Working Hours';
  slbCalendarZoomIn = 'Zoom In';
  slbCalendarZoomOut = 'Zoom Out';
  slbOpenEventEditDialog = 'Open';
  slbRecurrence = 'Recurrence';
  sLinks = 'Links';
  sMailBoxesFieldName = 'Name';
  sMailForward = 'Forward';
  sMailNew = 'New Mail';
  sMailPriorityHigh = 'High priority';
  sMailPriorityLow = 'Low priority';
  sMailPriorityMedium = 'Medium priority';
  sMailReply = 'Reply';
  sMailReplyAll = 'Reply All';
  sMailUnreadState = 'Unread';
  sMainMenuCalendarCaption = 'Calendar';
  sMainMenuCustomersCaption = 'Customers';
  sMainMenuEmployeesCaption = 'Employees';
  sMainMenuLanguageCaption = 'Language';
  sMainMenuMailCaption = 'Mail';
  sMainMenuMyWorldCaption = 'MY WORLD';
  sMainMenuOperationsCaption = 'OPERATIONS';
  sMainMenuProductsCaption = 'Products';
  sMainMenuSalesCaption = 'Sales';
  sMainMenuTasksCaption = 'Tasks';
  sMessage = 'Message';
  sMessages = 'Messages';
  sMiddleName = 'Middle Name';
  sMiss = 'Miss';
  sMobilePhoneLabel = 'MOBILE PHONE';
  sMonitors = 'Monitors';
  sMonthlySalesColumn = 'Monthly Sales (FY2015)';
  sMr = 'Mr';
  sMrs = 'Mrs';
  sMs = 'Ms';
  sName = 'Name';
  sNameLabel = 'NAME';
  sNavigation = 'Navigation';
  sNewAppointment = 'New App&ointment';
  sNewButton = 'New';
  sNewEdit = 'New / Edit';
  sNewMailDescription = 'Create a new mail';
  sNewRespondGroup = 'New / Respond';
  sNormal = 'Normal';
  sNotes = 'Notes';
  sNotesLabel = 'NOTES';
  sOfficeSearchBoxNullString = 'Type a command to execute...';
  sOpen = 'Open';
  sOpportunitiesColumn = 'Opportunities';
  sOpportunitiesLabel = 'OPPORTUNITIES';
  sOptionsBarCaption = 'Options';
  sOrderDateColumn = 'Order Date';
  sOrderDateLabel = 'ORDER DATE';
  sOwnedByColumn = 'Owned By';
  sOwnerLabel = 'OWNER';
  sParagraph = 'Paragraph';
  sPasteHintDescription = 'Paste the contents of the Clipboard.';
  sPDFFile = 'PDF File';
  sPDFFileDescription = 'Adobe Portable Document Format';
  sPercentageColumn = 'Percentage';
  sPercentComplete = 'Percent Complete';
  sPersonalProfile = 'Personal Profile';
  sPhoneColumn = 'Phone';
  sPhoneLabel = 'PHONE';
  sPrefixLabel = 'PREFIX';
  sPrintButton = 'Print';
  sPrinterProperties = 'Printer Properties';
  sPriorityColumn = 'Priority';
  sPriorityDescription = 'Set priority for current mail';
  sPriorityHigh = 'High';
  sPriorityHighPriority = 'High Priority';
  sPriorityLabel = 'PRIORITY';
  sPriorityLow = 'Low';
  sPriorityNormal = 'Normal';
  sPriorityUrgent = 'Urgent';
  sProductCategoriesFilterCaption = ' PRODUCT Categories';
  sProductEngineerLabel = 'PRODUCT ENGINEER';
  sProductionStartDateLabel = 'PRODUCTION START DATE';
  sProductsSubMenu21inchMonitorCaption = '21inch Monitor';
  sProductsSubMenu50inchPlasmaCaption = '50inch Plasma';
  sProductsSubMenuHDVideoPlayerCaption = 'HD Video Player';
  sProductsSubMenuRemoteControlCaption = 'Remote Control';
  sProfileLabel = 'PROFILE';
  sProjectors = 'Projectors';
  sPurchaseDateLabel = 'PURCHASE ORDER';
  sQuantityColumn = 'Quantity';
  sRatailPriceLabel = 'RETAIL PRICE';
  sReading = 'Reading';
  sReceived = 'Received';
  sReloadConfirmation = 'Click OK to reload the entity and lose unsaved changes. Click Cancel to continue editing data.';
  sReplaceHintDescription = 'Replace text in the document.';
  sReplyDescription = 'Reply to the sender of current message';
  sRetailPriceColumn = 'Retail Price';
  sRotate = 'Rotate';
  sSaleLabel = 'SALE';
  sSalePriceColumn = 'Sale Price';
  sSalePriceLabel = 'SALE PRICE';
  sSalesColumn = 'Sales (FY%s)';
  sSalesLabel = 'SALES';
  sSaveButton = 'Save';
  sSaveChangesConfirmation = 'Do you want to save changes?';
  sSearch = 'Search';
  sSend = 'Send';
  sSendMessage = 'Send message';
  sSent = 'Sent';
  sShippingLabel = 'SHIPPING';
  ssiLabelAs = '&Label As';
  ssiShowTimeAs = '&Show Time As';
  sSkypeLabel = 'SKYPE';
  sSplashScreenInitializeMessage = 'Initializing data for demo. Please wait...';
  sStartDate = 'Start Date';
  sStartDateLabel = 'START DATE';
  sStateColumn = 'State';
  sStateLabel = 'STATE';
  sStatusColumn = 'Status';
  sStatusLabel = 'STATUS';
  sStoreColumn = 'Store';
  sStoreLabel = 'STORE';
  sSubjectColumn = 'Subject';
  sSubjectLabel = 'SUBJECT';
  sSubMenuCustomFilterCaption = 'CUSTOM FILTER';
  sSupport = 'Support';
  sSupportEngineerLabel = 'SUPPORT ENGINEER';
  sSymbols = 'Symbols';
  sTags = 'Tags';
  stAppointmentOpenDescription = 'Open the selected appointment.';
  stAppointmentOpenHeader = 'Open';
  stAppointmentRecurrenceHeader = 'Recurrence';
  stAppointmentReminderHeader = 'Reminder';
  sTaskCategoryHouseChores = 'House Chores';
  sTaskCategoryOffice = 'Work';
  sTaskCategoryShopping = 'Shopping';
  sTaskEdit = 'Edit Task';
  sTaskNew = 'New Task';
  sTasks = 'Tasks';
  sTasksLabel = 'TASKS';
  sTaskStatusDeffered = 'Deffered';
  sTaskStatusInProgress = 'In Progress';
  sTaskStatusNeedAssistance = 'Need Assistance';
  sTaskStatusNotStarted = 'Not Started';
  sTaskStatusWaitingOnSomeoneElse = 'Waiting On Someone Else';
  stCalendarBackDescription = 'Step back in time as suggested by the current view.';
  stCalendarBackHeader = 'Backward';
  stCalendarForwardDescription = 'Advance forward in time as suggested by the current view.';
  stCalendarForwardHeader = 'Forward';
  stCalendarGoToTodayDescription = 'Change the date displayed in the current view to the current date.';
  stCalendarGoToTodayHeader = 'Go to Today';
  stCalendarGroupDateDescription = 'Group appointments by date.';
  stCalendarGroupDateHeader = 'Group by Date';
  stCalendarGroupNoneDescription = 'Ungroup appointments.';
  stCalendarGroupNoneHeader = 'Group by None';
  stCalendarGroupResourceDescription = 'Group appointments by resource.';
  stCalendarGroupResourceHeader = 'Group by Resource';
  stCalendarLayoutCompressWeekendDescription = 'Show Saturday and Sunday compressed into a single column.';
  stCalendarLayoutCompressWeekendHeader = 'Compress Weekend';
  stCalendarLayoutTimeScalesDescription = 'Change the time scale.';
  stCalendarLayoutTimeScalesHeader = 'Time Scales';
  stCalendarLayoutWorkingHoursDescription = 'Show only working hours in the calendar.';
  stCalendarLayoutWorkingHoursHeader = 'Working Hours';
  stCalendarNewDescription = 'Create a new appointment.';
  stCalendarNewHeader = 'New Appointment';
  stCalendarNewRecurringDescription = 'Create a new recurring appointment.';
  stCalendarNewRecurringHeader = 'New Recurring Appointment';
  stCalendarViewAgendaDescription = 'Switch to the Agenda view. Displays a list of upcoming events.';
  stCalendarViewAgendaHeader = 'Agenda View';
  stCalendarViewDayDescription = 'Switch to the Day view. The most detailed view of appointments for a specific day(s).';
  stCalendarViewDayHeader = 'Day View';
  stCalendarViewMonthDescription = 'Switch to the Month (Multi-Week) view. Calendar view useful for long-term plans.';
  stCalendarViewMonthHeader = 'Month View';
  stCalendarViewTimelineDescription = 'Switch to the Timeline view. Plots appointments in relation to time.';
  stCalendarViewTimelineHeader = 'Timeline View';
  stCalendarViewWeekDescription = 'Switch to the Week view. Arranges appointments for a particular week in a compact form.';
  stCalendarViewWeekHeader = 'Week View';
  stCalendarViewWeekWorkHeader = 'Work Week View';
  stCalendarZoomInDescription = 'Perform scaling up to display content in more detail.';
  stCalendarZoomInHeader = 'Zoom In';
  stCalendarZoomOutDescription = 'Perform scaling down to display a broader look of the View.';
  stCalendarZoomOutHeader = 'Zoom Out';
  stContactDeleteDescription = 'Delete this contact.';
  stContactEditDescription = 'Edit this contact.';
  stContactEditHeader = 'Edit Contact';
  stContactNewDescription = 'Create a new contact.';
  stContactNewHeader = 'New Contact';
  sTelevisions = 'Televisions';
  sTextFile = 'Text File';
  sTextFileDescription = 'Plain Text';
  stFeedRefreshDescription = 'Reload this feed from the server.';
  stFeedRefreshHeader = 'Refresh';
  stFlipDescription = 'Flip the layout of controls around a vertical axis.';
  stFlipHeader = 'Flip Layout';
  stFontDialogHeader = 'Font';
  sTitleColumn = 'Title';
  sTitleLabel = 'TITLE';
  sTitleProf = 'Prof.';
  stMailDeleteItemDescription = 'Delete this item.';
  stMailForwardDescription = 'Forward this item to someone else.';
  stMailForwardHeader = 'Forward';
  stMailNewDescription = 'Create a new mail.';
  stMailNewHeader = 'New Mail';
  stMailPriorityDescription = 'Set priority for this item.';
  stMailPriorityHeader = 'Priority';
  stMailReplyAllDescription = 'Reply to the sender and all other recipients of this message.';
  stMailReplyAllHeader = 'Reply All';
  stMailReplyDescription = 'Reply to the sender of this message.';
  stMailReplyHeader = 'Reply';
  stMailUnreadHeader = 'Unread/Read';
  sTo = 'To';
  sTo_From = 'To/From';
  sTotalAmountColumn = 'Total Amount';
  sTotalInventoryLabel = 'TOTAL INVENTORY';
  sTotalOfTasksColumn = 'TOTAL # OF TASKS';
  sTotalSalesLabel = 'TOTAL SALES';
  stRotateDescription = 'Rotate the layout of controls.';
  stRotateHeader = 'Rotate Layout';
  stTaskDeleteDescription = 'Delete this task.';
  stTaskEditDescription = 'Edit this task.';
  stTaskEditHeader = 'Edit Task';
  stTaskFollowCustomDescription = 'Flag this item as a task with custom due date.';
  stTaskFollowCustomHeader = 'Custom';
  stTaskFollowNextWeekDescription = 'Flag this item as a task for next week.';
  stTaskFollowNextWeekHeader = 'Next Week';
  stTaskFollowNoDateDescription = 'Flag this item as a task with no due date.';
  stTaskFollowNoDateHeader = 'No Date';
  stTaskFollowThisWeekDescription = 'Flag this item as a task with a due date at the end of the work week';
  stTaskFollowThisWeekHeader = 'This Week';
  stTaskFollowTodayDescription = 'Flag this item as a task with a due date of today.';
  stTaskFollowTomorrowDescription = 'Flag this item as a task with a due date of tomorrow.';
  stTaskFollowTomorrowHeader = 'Tomorrow';
  stTaskNewDescription = 'Create a new task.';
  stTaskNewHeader = 'New Task';
  stViewNavigationDescription = 'Switch between modules.';
  stViewNavigationHeader = 'Navigation';
  sUnderlineHintDescription = 'Draw a line below the text.';
  sUndo = '&Undo';
  sUnitPriceColumn = 'Unit Price';
  sUnreadReadDescription = 'If current mail is marked as unread mark it as read.' + #13#10 + 'If current mail is marked as read mark it as though you haven''t read it yet';
  sVideoPlayers = 'Video Players';
  sViewButton = 'View';
  sWebinars = 'Webinars';
  sXLSFile = 'XLS File';
  sXLSFileDescription = 'Microsoft Excel 2000-2003 Workbook';
  sXLSXFile = 'XLSX File';
  sXLSXFileDescription = 'Microsoft Excel 2007 Workbook';
  sXMLFile = 'XML File';
  sXMLFileDescription = 'XML File';
  sZipCodeColumn = 'Zip Code';
  sZipCodeLabel = 'ZIP CODE';
  sZoomInButton = 'Zoom In';
  sZoomOutButton = 'Zoom Out';

implementation

procedure AddResourceStringNames(AProduct: TdxProductResourceStrings);
begin
  AProduct.Add('sActionsBarCaption', @sActionsBarCaption);
  AProduct.Add('sAddressColumn', @sAddressColumn);
  AProduct.Add('sAddressLabel', @sAddressLabel);
  AProduct.Add('sAddressLine', @sAddressLine);
  AProduct.Add('sAgendaOptions', @sAgendaOptions);
  AProduct.Add('sAlignTextCenter', @sAlignTextCenter);
  AProduct.Add('sAlignTextCenterHintDescription', @sAlignTextCenterHintDescription);
  AProduct.Add('sAlignTextLeft', @sAlignTextLeft);
  AProduct.Add('sAlignTextLeftHintDescription', @sAlignTextLeftHintDescription);
  AProduct.Add('sAlignTextRight', @sAlignTextRight);
  AProduct.Add('sAlignTextRightDescription', @sAlignTextRightDescription);
  AProduct.Add('sAscendingButton', @sAscendingButton);
  AProduct.Add('sAssignedEmployeesTab', @sAssignedEmployeesTab);
  AProduct.Add('sAssignedToColumn', @sAssignedToColumn);
  AProduct.Add('sAssignedToLabel', @sAssignedToLabel);
  AProduct.Add('sAutomation', @sAutomation);
  AProduct.Add('sAvailableForSaleLabel', @sAvailableForSaleLabel);
  AProduct.Add('sBackorderColumn', @sBackorderColumn);
  AProduct.Add('sBackOrdersLabel', @sBackOrdersLabel);
  AProduct.Add('sBarButtonCopyHint', @sBarButtonCopyHint);
  AProduct.Add('sBarButtonCutHint', @sBarButtonCutHint);
  AProduct.Add('sBarButtonFindHint', @sBarButtonFindHint);
  AProduct.Add('sBarButtonPasteHint', @sBarButtonPasteHint);
  AProduct.Add('sBarButtonReplaceHint', @sBarButtonReplaceHint);
  AProduct.Add('sBarButtonSaveHint', @sBarButtonSaveHint);
  AProduct.Add('sBarButtonSelectAllHint', @sBarButtonSelectAllHint);
  AProduct.Add('sbbBusy', @sbbBusy);
  AProduct.Add('sbbFree', @sbbFree);
  AProduct.Add('sbBold', @sbBold);
  AProduct.Add('sbbOutOfOffice', @sbbOutOfOffice);
  AProduct.Add('sbbTentative', @sbbTentative);
  AProduct.Add('sbCalendarTimelines10Minutes', @sbCalendarTimelines10Minutes);
  AProduct.Add('sbCalendarTimelines15Minutes', @sbCalendarTimelines15Minutes);
  AProduct.Add('sbCalendarTimelines30Minutes', @sbCalendarTimelines30Minutes);
  AProduct.Add('sbCalendarTimelines5Minutes', @sbCalendarTimelines5Minutes);
  AProduct.Add('sbCalendarTimelines60Minutes', @sbCalendarTimelines60Minutes);
  AProduct.Add('sbCalendarTimelines6Minutes', @sbCalendarTimelines6Minutes);
  AProduct.Add('sbCalendarTimelinesDay', @sbCalendarTimelinesDay);
  AProduct.Add('sbCalendarTimelinesMonth', @sbCalendarTimelinesMonth);
  AProduct.Add('sbCalendarTimelinesWeek', @sbCalendarTimelinesWeek);
  AProduct.Add('sBillingAddressLabel', @sBillingAddressLabel);
  AProduct.Add('sBirthDate', @sBirthDate);
  AProduct.Add('sbItalic', @sbItalic);
  AProduct.Add('sBoldHintDescription', @sBoldHintDescription);
  AProduct.Add('sBulletedList', @sBulletedList);
  AProduct.Add('sbUnderline', @sbUnderline);
  AProduct.Add('sCancelButton', @sCancelButton);
  AProduct.Add('sCategory', @sCategory);
  AProduct.Add('sCategoryLabel', @sCategoryLabel);
  AProduct.Add('scbReminder', @scbReminder);
  AProduct.Add('sCityColumn', @sCityColumn);
  AProduct.Add('sCityLabel', @sCityLabel);
  AProduct.Add('sClear', @sClear);
  AProduct.Add('sClipboard', @sClipboard);
  AProduct.Add('sCloseButton', @sCloseButton);
  AProduct.Add('sCompanyLabel', @sCompanyLabel);
  AProduct.Add('sComplete', @sComplete);
  AProduct.Add('sCompleteColumn', @sCompleteColumn);
  AProduct.Add('sCompleted', @sCompleted);
  AProduct.Add('sCompleteLabel', @sCompleteLabel);
  AProduct.Add('sContactEdit', @sContactEdit);
  AProduct.Add('sContactNew', @sContactNew);
  AProduct.Add('sContactsColumn', @sContactsColumn);
  AProduct.Add('sContactViewAlphabetical', @sContactViewAlphabetical);
  AProduct.Add('sContactViewByState', @sContactViewByState);
  AProduct.Add('sContactViewCard', @sContactViewCard);
  AProduct.Add('sContactViewList', @sContactViewList);
  AProduct.Add('sCopyHintDescription', @sCopyHintDescription);
  AProduct.Add('sCostColumn', @sCostColumn);
  AProduct.Add('sCostLabel', @sCostLabel);
  AProduct.Add('sCreatedByColumn', @sCreatedByColumn);
  AProduct.Add('sCreatedOnColumn', @sCreatedOnColumn);
  AProduct.Add('sCurrentInventoryLabel', @sCurrentInventoryLabel);
  AProduct.Add('sCurrentView', @sCurrentView);
  AProduct.Add('sCustomersLabel', @sCustomersLabel);
  AProduct.Add('sCustomersSubMenuAllCustomersCaption', @sCustomersSubMenuAllCustomersCaption);
  AProduct.Add('sCustomersSubMenuJohnsAccountCaption', @sCustomersSubMenuJohnsAccountCaption);
  AProduct.Add('sCustomersSubMenuMyAccountCaption', @sCustomersSubMenuMyAccountCaption);
  AProduct.Add('sCustomersSubMenuTopStoresCaption', @sCustomersSubMenuTopStoresCaption);
  AProduct.Add('sCutHintDescription', @sCutHintDescription);
  AProduct.Add('sDate', @sDate);
  AProduct.Add('sDateCompleted', @sDateCompleted);
  AProduct.Add('sDateCreated', @sDateCreated);
  AProduct.Add('sDeleteConfirmation', @sDeleteConfirmation);
  AProduct.Add('sDeleteItemDescription', @sDeleteItemDescription);
  AProduct.Add('sDepartmentColumn', @sDepartmentColumn);
  AProduct.Add('sDepartmentLabel', @sDepartmentLabel);
  AProduct.Add('sDescendingButton', @sDescendingButton);
  AProduct.Add('sDescription', @sDescription);
  AProduct.Add('sDescriptionLabel', @sDescriptionLabel);
  AProduct.Add('sDevelopment', @sDevelopment);
  AProduct.Add('sDiscountColumn', @sDiscountColumn);
  AProduct.Add('sDOBLabel', @sDOBLabel);
  AProduct.Add('sDr', @sDr);
  AProduct.Add('sDueDateColumn', @sDueDateColumn);
  AProduct.Add('sDueDateLabel', @sDueDateLabel);
  AProduct.Add('sdxBarButtonCopy', @sdxBarButtonCopy);
  AProduct.Add('sdxBarButtonCut', @sdxBarButtonCut);
  AProduct.Add('sdxBarButtonFind', @sdxBarButtonFind);
  AProduct.Add('sdxBarButtonPaste', @sdxBarButtonPaste);
  AProduct.Add('sdxBarButtonPrint', @sdxBarButtonPrint);
  AProduct.Add('sdxBarButtonReplace', @sdxBarButtonReplace);
  AProduct.Add('sdxBarButtonSave', @sdxBarButtonSave);
  AProduct.Add('sdxBarButtonSelectAll', @sdxBarButtonSelectAll);
  AProduct.Add('sEditButton', @sEditButton);
  AProduct.Add('sEditing', @sEditing);
  AProduct.Add('sEditTaskFormCaption', @sEditTaskFormCaption);
  AProduct.Add('sEmail', @sEmail);
  AProduct.Add('sEmailLabel', @sEmailLabel);
  AProduct.Add('sEmployeeFilterCaption', @sEmployeeFilterCaption);
  AProduct.Add('sEmployeeStatusCommission', @sEmployeeStatusCommission);
  AProduct.Add('sEmployeeStatusContract', @sEmployeeStatusContract);
  AProduct.Add('sEmployeeStatusOnLeave', @sEmployeeStatusOnLeave);
  AProduct.Add('sEmployeeStatusSalaried', @sEmployeeStatusSalaried);
  AProduct.Add('sEmployeeStatusTerminated', @sEmployeeStatusTerminated);
  AProduct.Add('sExit', @sExit);
  AProduct.Add('sExport', @sExport);
  AProduct.Add('sFamily', @sFamily);
  AProduct.Add('sFaxColumn', @sFaxColumn);
  AProduct.Add('sFaxLabel', @sFaxLabel);
  AProduct.Add('sFilterAllCaption', @sFilterAllCaption);
  AProduct.Add('sFilterTaskCaption', @sFilterTaskCaption);
  AProduct.Add('sFindHintDescription', @sFindHintDescription);
  AProduct.Add('sFirstName', @sFirstName);
  AProduct.Add('sFirstNameLabel', @sFirstNameLabel);
  AProduct.Add('sFlagStatus', @sFlagStatus);
  AProduct.Add('sFlip', @sFlip);
  AProduct.Add('sFollowCustom', @sFollowCustom);
  AProduct.Add('sFollowNextWeek', @sFollowNextWeek);
  AProduct.Add('sFollowNoDate', @sFollowNoDate);
  AProduct.Add('sFollowThisWeek', @sFollowThisWeek);
  AProduct.Add('sFollowTomorrow', @sFollowTomorrow);
  AProduct.Add('sFollowUp', @sFollowUp);
  AProduct.Add('sFontColor', @sFontColor);
  AProduct.Add('sForwardDescription', @sForwardDescription);
  AProduct.Add('sFrameBar1BarCaption', @sFrameBar1BarCaption);
  AProduct.Add('sFrameBar2BarCaption', @sFrameBar2BarCaption);
  AProduct.Add('sFrameBar3BarCaption', @sFrameBar3BarCaption);
  AProduct.Add('sFrameBar4BarCaption', @sFrameBar4BarCaption);
  AProduct.Add('sFrameBar5BarCaption', @sFrameBar5BarCaption);
  AProduct.Add('sFrom', @sFrom);
  AProduct.Add('sFullNameColumn', @sFullNameColumn);
  AProduct.Add('sFullNameLabel', @sFullNameLabel);
  AProduct.Add('sGrandTotalLabel', @sGrandTotalLabel);
  AProduct.Add('sHighlighting', @sHighlighting);
  AProduct.Add('sHireDateLabel', @sHireDateLabel);
  AProduct.Add('sHomePhoneLabel', @sHomePhoneLabel);
  AProduct.Add('sHomeTabCaption', @sHomeTabCaption);
  AProduct.Add('sHTMLFile', @sHTMLFile);
  AProduct.Add('sHTMLFileDescription', @sHTMLFileDescription);
  AProduct.Add('sImportance', @sImportance);
  AProduct.Add('sInfo', @sInfo);
  AProduct.Add('sInventoryColumn', @sInventoryColumn);
  AProduct.Add('sInvoiceColumn', @sInvoiceColumn);
  AProduct.Add('sItalicHintDescription', @sItalicHintDescription);
  AProduct.Add('sItemCountInfo', @sItemCountInfo);
  AProduct.Add('sLanguageSubMenuArabicCaption', @sLanguageSubMenuArabicCaption);
  AProduct.Add('sLanguageSubMenuEnglishCaption', @sLanguageSubMenuEnglishCaption);
  AProduct.Add('sLanguageSubMenuHebrewCaption', @sLanguageSubMenuHebrewCaption);
  AProduct.Add('sLanguageSubMenuLTRCaption', @sLanguageSubMenuLTRCaption);
  AProduct.Add('sLanguageSubMenuRTLCaption', @sLanguageSubMenuRTLCaption);
  AProduct.Add('sLastName', @sLastName);
  AProduct.Add('sLastNameLabel', @sLastNameLabel);
  AProduct.Add('sLayout', @sLayout);
  AProduct.Add('slbCalendarGoToDay', @slbCalendarGoToDay);
  AProduct.Add('slbCalendarGroupByDate', @slbCalendarGroupByDate);
  AProduct.Add('slbCalendarGroupByResource', @slbCalendarGroupByResource);
  AProduct.Add('slbCalendarLayoutCompressWeekend', @slbCalendarLayoutCompressWeekend);
  AProduct.Add('slbCalendarNavigateNext', @slbCalendarNavigateNext);
  AProduct.Add('slbCalendarNavigatePrior', @slbCalendarNavigatePrior);
  AProduct.Add('slbCalendarNewRepeatingEvent', @slbCalendarNewRepeatingEvent);
  AProduct.Add('slbCalendarNoGroup', @slbCalendarNoGroup);
  AProduct.Add('slbCalendarViewAgenda', @slbCalendarViewAgenda);
  AProduct.Add('slbCalendarViewDay', @slbCalendarViewDay);
  AProduct.Add('slbCalendarViewDayTimelines', @slbCalendarViewDayTimelines);
  AProduct.Add('slbCalendarViewMonth', @slbCalendarViewMonth);
  AProduct.Add('slbCalendarViewTimeline', @slbCalendarViewTimeline);
  AProduct.Add('slbCalendarViewWeek', @slbCalendarViewWeek);
  AProduct.Add('slbCalendarViewWorkWeek', @slbCalendarViewWorkWeek);
  AProduct.Add('slbCalendarWorktime', @slbCalendarWorktime);
  AProduct.Add('slbCalendarZoomIn', @slbCalendarZoomIn);
  AProduct.Add('slbCalendarZoomOut', @slbCalendarZoomOut);
  AProduct.Add('slbOpenEventEditDialog', @slbOpenEventEditDialog);
  AProduct.Add('slbRecurrence', @slbRecurrence);
  AProduct.Add('sLinks', @sLinks);
  AProduct.Add('sMailBoxesFieldName', @sMailBoxesFieldName);
  AProduct.Add('sMailForward', @sMailForward);
  AProduct.Add('sMailNew', @sMailNew);
  AProduct.Add('sMailPriorityHigh', @sMailPriorityHigh);
  AProduct.Add('sMailPriorityLow', @sMailPriorityLow);
  AProduct.Add('sMailPriorityMedium', @sMailPriorityMedium);
  AProduct.Add('sMailReply', @sMailReply);
  AProduct.Add('sMailReplyAll', @sMailReplyAll);
  AProduct.Add('sMailUnreadState', @sMailUnreadState);
  AProduct.Add('sMainMenuCalendarCaption', @sMainMenuCalendarCaption);
  AProduct.Add('sMainMenuCustomersCaption', @sMainMenuCustomersCaption);
  AProduct.Add('sMainMenuEmployeesCaption', @sMainMenuEmployeesCaption);
  AProduct.Add('sMainMenuLanguageCaption', @sMainMenuLanguageCaption);
  AProduct.Add('sMainMenuMailCaption', @sMainMenuMailCaption);
  AProduct.Add('sMainMenuMyWorldCaption', @sMainMenuMyWorldCaption);
  AProduct.Add('sMainMenuOperationsCaption', @sMainMenuOperationsCaption);
  AProduct.Add('sMainMenuProductsCaption', @sMainMenuProductsCaption);
  AProduct.Add('sMainMenuSalesCaption', @sMainMenuSalesCaption);
  AProduct.Add('sMainMenuTasksCaption', @sMainMenuTasksCaption);
  AProduct.Add('sMessage', @sMessage);
  AProduct.Add('sMessages', @sMessages);
  AProduct.Add('sMiddleName', @sMiddleName);
  AProduct.Add('sMiss', @sMiss);
  AProduct.Add('sMobilePhoneLabel', @sMobilePhoneLabel);
  AProduct.Add('sMonitors', @sMonitors);
  AProduct.Add('sMonthlySalesColumn', @sMonthlySalesColumn);
  AProduct.Add('sMr', @sMr);
  AProduct.Add('sMrs', @sMrs);
  AProduct.Add('sMs', @sMs);
  AProduct.Add('sName', @sName);
  AProduct.Add('sNameLabel', @sNameLabel);
  AProduct.Add('sNavigation', @sNavigation);
  AProduct.Add('sNewAppointment', @sNewAppointment);
  AProduct.Add('sNewButton', @sNewButton);
  AProduct.Add('sNewEdit', @sNewEdit);
  AProduct.Add('sNewMailDescription', @sNewMailDescription);
  AProduct.Add('sNewRespondGroup', @sNewRespondGroup);
  AProduct.Add('sNormal', @sNormal);
  AProduct.Add('sNotes', @sNotes);
  AProduct.Add('sNotesLabel', @sNotesLabel);
  AProduct.Add('sOfficeSearchBoxNullString', @sOfficeSearchBoxNullString);
  AProduct.Add('sOpen', @sOpen);
  AProduct.Add('sOpportunitiesColumn', @sOpportunitiesColumn);
  AProduct.Add('sOpportunitiesLabel', @sOpportunitiesLabel);
  AProduct.Add('sOptionsBarCaption', @sOptionsBarCaption);
  AProduct.Add('sOrderDateColumn', @sOrderDateColumn);
  AProduct.Add('sOrderDateLabel', @sOrderDateLabel);
  AProduct.Add('sOwnedByColumn', @sOwnedByColumn);
  AProduct.Add('sOwnerLabel', @sOwnerLabel);
  AProduct.Add('sParagraph', @sParagraph);
  AProduct.Add('sPasteHintDescription', @sPasteHintDescription);
  AProduct.Add('sPDFFile', @sPDFFile);
  AProduct.Add('sPDFFileDescription', @sPDFFileDescription);
  AProduct.Add('sPercentageColumn', @sPercentageColumn);
  AProduct.Add('sPercentComplete', @sPercentComplete);
  AProduct.Add('sPersonalProfile', @sPersonalProfile);
  AProduct.Add('sPhoneColumn', @sPhoneColumn);
  AProduct.Add('sPhoneLabel', @sPhoneLabel);
  AProduct.Add('sPrefixLabel', @sPrefixLabel);
  AProduct.Add('sPrintButton', @sPrintButton);
  AProduct.Add('sPrinterProperties', @sPrinterProperties);
  AProduct.Add('sPriorityColumn', @sPriorityColumn);
  AProduct.Add('sPriorityDescription', @sPriorityDescription);
  AProduct.Add('sPriorityHigh', @sPriorityHigh);
  AProduct.Add('sPriorityHighPriority', @sPriorityHighPriority);
  AProduct.Add('sPriorityLabel', @sPriorityLabel);
  AProduct.Add('sPriorityLow', @sPriorityLow);
  AProduct.Add('sPriorityNormal', @sPriorityNormal);
  AProduct.Add('sPriorityUrgent', @sPriorityUrgent);
  AProduct.Add('sProductCategoriesFilterCaption', @sProductCategoriesFilterCaption);
  AProduct.Add('sProductEngineerLabel', @sProductEngineerLabel);
  AProduct.Add('sProductionStartDateLabel', @sProductionStartDateLabel);
  AProduct.Add('sProductsSubMenu21inchMonitorCaption', @sProductsSubMenu21inchMonitorCaption);
  AProduct.Add('sProductsSubMenu50inchPlasmaCaption', @sProductsSubMenu50inchPlasmaCaption);
  AProduct.Add('sProductsSubMenuHDVideoPlayerCaption', @sProductsSubMenuHDVideoPlayerCaption);
  AProduct.Add('sProductsSubMenuRemoteControlCaption', @sProductsSubMenuRemoteControlCaption);
  AProduct.Add('sProfileLabel', @sProfileLabel);
  AProduct.Add('sProjectors', @sProjectors);
  AProduct.Add('sPurchaseDateLabel', @sPurchaseDateLabel);
  AProduct.Add('sQuantityColumn', @sQuantityColumn);
  AProduct.Add('sRatailPriceLabel', @sRatailPriceLabel);
  AProduct.Add('sReading', @sReading);
  AProduct.Add('sReceived', @sReceived);
  AProduct.Add('sReloadConfirmation', @sReloadConfirmation);
  AProduct.Add('sReplaceHintDescription', @sReplaceHintDescription);
  AProduct.Add('sReplyDescription', @sReplyDescription);
  AProduct.Add('sRetailPriceColumn', @sRetailPriceColumn);
  AProduct.Add('sRotate', @sRotate);
  AProduct.Add('sSaleLabel', @sSaleLabel);
  AProduct.Add('sSalePriceColumn', @sSalePriceColumn);
  AProduct.Add('sSalePriceLabel', @sSalePriceLabel);
  AProduct.Add('sSalesColumn', @sSalesColumn);
  AProduct.Add('sSalesLabel', @sSalesLabel);
  AProduct.Add('sSaveButton', @sSaveButton);
  AProduct.Add('sSaveChangesConfirmation', @sSaveChangesConfirmation);
  AProduct.Add('sSearch', @sSearch);
  AProduct.Add('sSend', @sSend);
  AProduct.Add('sSendMessage', @sSendMessage);
  AProduct.Add('sSent', @sSent);
  AProduct.Add('sShippingLabel', @sShippingLabel);
  AProduct.Add('ssiLabelAs', @ssiLabelAs);
  AProduct.Add('ssiShowTimeAs', @ssiShowTimeAs);
  AProduct.Add('sSkypeLabel', @sSkypeLabel);
  AProduct.Add('sSplashScreenInitializeMessage', @sSplashScreenInitializeMessage);
  AProduct.Add('sStartDate', @sStartDate);
  AProduct.Add('sStartDateLabel', @sStartDateLabel);
  AProduct.Add('sStateColumn', @sStateColumn);
  AProduct.Add('sStateLabel', @sStateLabel);
  AProduct.Add('sStatusColumn', @sStatusColumn);
  AProduct.Add('sStatusLabel', @sStatusLabel);
  AProduct.Add('sStoreColumn', @sStoreColumn);
  AProduct.Add('sStoreLabel', @sStoreLabel);
  AProduct.Add('sSubjectColumn', @sSubjectColumn);
  AProduct.Add('sSubjectLabel', @sSubjectLabel);
  AProduct.Add('sSubMenuCustomFilterCaption', @sSubMenuCustomFilterCaption);
  AProduct.Add('sSupport', @sSupport);
  AProduct.Add('sSupportEngineerLabel', @sSupportEngineerLabel);
  AProduct.Add('sSymbols', @sSymbols);
  AProduct.Add('sTags', @sTags);
  AProduct.Add('stAppointmentOpenDescription', @stAppointmentOpenDescription);
  AProduct.Add('stAppointmentOpenHeader', @stAppointmentOpenHeader);
  AProduct.Add('stAppointmentRecurrenceHeader', @stAppointmentRecurrenceHeader);
  AProduct.Add('stAppointmentReminderHeader', @stAppointmentReminderHeader);
  AProduct.Add('sTaskCategoryHouseChores', @sTaskCategoryHouseChores);
  AProduct.Add('sTaskCategoryOffice', @sTaskCategoryOffice);
  AProduct.Add('sTaskCategoryShopping', @sTaskCategoryShopping);
  AProduct.Add('sTaskEdit', @sTaskEdit);
  AProduct.Add('sTaskNew', @sTaskNew);
  AProduct.Add('sTasks', @sTasks);
  AProduct.Add('sTasksLabel', @sTasksLabel);
  AProduct.Add('sTaskStatusDeffered', @sTaskStatusDeffered);
  AProduct.Add('sTaskStatusInProgress', @sTaskStatusInProgress);
  AProduct.Add('sTaskStatusNeedAssistance', @sTaskStatusNeedAssistance);
  AProduct.Add('sTaskStatusNotStarted', @sTaskStatusNotStarted);
  AProduct.Add('sTaskStatusWaitingOnSomeoneElse', @sTaskStatusWaitingOnSomeoneElse);
  AProduct.Add('stCalendarBackDescription', @stCalendarBackDescription);
  AProduct.Add('stCalendarBackHeader', @stCalendarBackHeader);
  AProduct.Add('stCalendarForwardDescription', @stCalendarForwardDescription);
  AProduct.Add('stCalendarForwardHeader', @stCalendarForwardHeader);
  AProduct.Add('stCalendarGoToTodayDescription', @stCalendarGoToTodayDescription);
  AProduct.Add('stCalendarGoToTodayHeader', @stCalendarGoToTodayHeader);
  AProduct.Add('stCalendarGroupDateDescription', @stCalendarGroupDateDescription);
  AProduct.Add('stCalendarGroupDateHeader', @stCalendarGroupDateHeader);
  AProduct.Add('stCalendarGroupNoneDescription', @stCalendarGroupNoneDescription);
  AProduct.Add('stCalendarGroupNoneHeader', @stCalendarGroupNoneHeader);
  AProduct.Add('stCalendarGroupResourceDescription', @stCalendarGroupResourceDescription);
  AProduct.Add('stCalendarGroupResourceHeader', @stCalendarGroupResourceHeader);
  AProduct.Add('stCalendarLayoutCompressWeekendDescription', @stCalendarLayoutCompressWeekendDescription);
  AProduct.Add('stCalendarLayoutCompressWeekendHeader', @stCalendarLayoutCompressWeekendHeader);
  AProduct.Add('stCalendarLayoutTimeScalesDescription', @stCalendarLayoutTimeScalesDescription);
  AProduct.Add('stCalendarLayoutTimeScalesHeader', @stCalendarLayoutTimeScalesHeader);
  AProduct.Add('stCalendarLayoutWorkingHoursDescription', @stCalendarLayoutWorkingHoursDescription);
  AProduct.Add('stCalendarLayoutWorkingHoursHeader', @stCalendarLayoutWorkingHoursHeader);
  AProduct.Add('stCalendarNewDescription', @stCalendarNewDescription);
  AProduct.Add('stCalendarNewHeader', @stCalendarNewHeader);
  AProduct.Add('stCalendarNewRecurringDescription', @stCalendarNewRecurringDescription);
  AProduct.Add('stCalendarNewRecurringHeader', @stCalendarNewRecurringHeader);
  AProduct.Add('stCalendarViewAgendaDescription', @stCalendarViewAgendaDescription);
  AProduct.Add('stCalendarViewAgendaHeader', @stCalendarViewAgendaHeader);
  AProduct.Add('stCalendarViewDayDescription', @stCalendarViewDayDescription);
  AProduct.Add('stCalendarViewDayHeader', @stCalendarViewDayHeader);
  AProduct.Add('stCalendarViewMonthDescription', @stCalendarViewMonthDescription);
  AProduct.Add('stCalendarViewMonthHeader', @stCalendarViewMonthHeader);
  AProduct.Add('stCalendarViewTimelineDescription', @stCalendarViewTimelineDescription);
  AProduct.Add('stCalendarViewTimelineHeader', @stCalendarViewTimelineHeader);
  AProduct.Add('stCalendarViewWeekDescription', @stCalendarViewWeekDescription);
  AProduct.Add('stCalendarViewWeekHeader', @stCalendarViewWeekHeader);
  AProduct.Add('stCalendarViewWeekWorkHeader', @stCalendarViewWeekWorkHeader);
  AProduct.Add('stCalendarZoomInDescription', @stCalendarZoomInDescription);
  AProduct.Add('stCalendarZoomInHeader', @stCalendarZoomInHeader);
  AProduct.Add('stCalendarZoomOutDescription', @stCalendarZoomOutDescription);
  AProduct.Add('stCalendarZoomOutHeader', @stCalendarZoomOutHeader);
  AProduct.Add('stContactDeleteDescription', @stContactDeleteDescription);
  AProduct.Add('stContactEditDescription', @stContactEditDescription);
  AProduct.Add('stContactEditHeader', @stContactEditHeader);
  AProduct.Add('stContactNewDescription', @stContactNewDescription);
  AProduct.Add('stContactNewHeader', @stContactNewHeader);
  AProduct.Add('sTelevisions', @sTelevisions);
  AProduct.Add('sTextFile', @sTextFile);
  AProduct.Add('sTextFileDescription', @sTextFileDescription);
  AProduct.Add('stFeedRefreshDescription', @stFeedRefreshDescription);
  AProduct.Add('stFeedRefreshHeader', @stFeedRefreshHeader);
  AProduct.Add('stFlipDescription', @stFlipDescription);
  AProduct.Add('stFlipHeader', @stFlipHeader);
  AProduct.Add('stFontDialogHeader', @stFontDialogHeader);
  AProduct.Add('sTitleColumn', @sTitleColumn);
  AProduct.Add('sTitleLabel', @sTitleLabel);
  AProduct.Add('sTitleProf', @sTitleProf);
  AProduct.Add('stMailDeleteItemDescription', @stMailDeleteItemDescription);
  AProduct.Add('stMailForwardDescription', @stMailForwardDescription);
  AProduct.Add('stMailForwardHeader', @stMailForwardHeader);
  AProduct.Add('stMailNewDescription', @stMailNewDescription);
  AProduct.Add('stMailNewHeader', @stMailNewHeader);
  AProduct.Add('stMailPriorityDescription', @stMailPriorityDescription);
  AProduct.Add('stMailPriorityHeader', @stMailPriorityHeader);
  AProduct.Add('stMailReplyAllDescription', @stMailReplyAllDescription);
  AProduct.Add('stMailReplyAllHeader', @stMailReplyAllHeader);
  AProduct.Add('stMailReplyDescription', @stMailReplyDescription);
  AProduct.Add('stMailReplyHeader', @stMailReplyHeader);
  AProduct.Add('stMailUnreadHeader', @stMailUnreadHeader);
  AProduct.Add('sTo', @sTo);
  AProduct.Add('sTo_From', @sTo_From);
  AProduct.Add('sTotalAmountColumn', @sTotalAmountColumn);
  AProduct.Add('sTotalInventoryLabel', @sTotalInventoryLabel);
  AProduct.Add('sTotalOfTasksColumn', @sTotalOfTasksColumn);
  AProduct.Add('sTotalSalesLabel', @sTotalSalesLabel);
  AProduct.Add('stRotateDescription', @stRotateDescription);
  AProduct.Add('stRotateHeader', @stRotateHeader);
  AProduct.Add('stTaskDeleteDescription', @stTaskDeleteDescription);
  AProduct.Add('stTaskEditDescription', @stTaskEditDescription);
  AProduct.Add('stTaskEditHeader', @stTaskEditHeader);
  AProduct.Add('stTaskFollowCustomDescription', @stTaskFollowCustomDescription);
  AProduct.Add('stTaskFollowCustomHeader', @stTaskFollowCustomHeader);
  AProduct.Add('stTaskFollowNextWeekDescription', @stTaskFollowNextWeekDescription);
  AProduct.Add('stTaskFollowNextWeekHeader', @stTaskFollowNextWeekHeader);
  AProduct.Add('stTaskFollowNoDateDescription', @stTaskFollowNoDateDescription);
  AProduct.Add('stTaskFollowNoDateHeader', @stTaskFollowNoDateHeader);
  AProduct.Add('stTaskFollowThisWeekDescription', @stTaskFollowThisWeekDescription);
  AProduct.Add('stTaskFollowThisWeekHeader', @stTaskFollowThisWeekHeader);
  AProduct.Add('stTaskFollowTodayDescription', @stTaskFollowTodayDescription);
  AProduct.Add('stTaskFollowTomorrowDescription', @stTaskFollowTomorrowDescription);
  AProduct.Add('stTaskFollowTomorrowHeader', @stTaskFollowTomorrowHeader);
  AProduct.Add('stTaskNewDescription', @stTaskNewDescription);
  AProduct.Add('stTaskNewHeader', @stTaskNewHeader);
  AProduct.Add('stViewNavigationDescription', @stViewNavigationDescription);
  AProduct.Add('stViewNavigationHeader', @stViewNavigationHeader);
  AProduct.Add('sUnderlineHintDescription', @sUnderlineHintDescription);
  AProduct.Add('sUndo', @sUndo);
  AProduct.Add('sUnitPriceColumn', @sUnitPriceColumn);
  AProduct.Add('sUnreadReadDescription', @sUnreadReadDescription);
  AProduct.Add('sVideoPlayers', @sVideoPlayers);
  AProduct.Add('sViewButton', @sViewButton);
  AProduct.Add('sWebinars', @sWebinars);
  AProduct.Add('sXLSFile', @sXLSFile);
  AProduct.Add('sXLSFileDescription', @sXLSFileDescription);
  AProduct.Add('sXLSXFile', @sXLSXFile);
  AProduct.Add('sXLSXFileDescription', @sXLSXFileDescription);
  AProduct.Add('sXMLFile', @sXMLFile);
  AProduct.Add('sXMLFileDescription', @sXMLFileDescription);
  AProduct.Add('sZipCodeColumn', @sZipCodeColumn);
  AProduct.Add('sZipCodeLabel', @sZipCodeLabel);
  AProduct.Add('sZoomInButton', @sZoomInButton);
  AProduct.Add('sZoomOutButton', @sZoomOutButton);
end;

initialization
  dxResourceStringsRepository.RegisterProduct('Custom Resource Strings', @AddResourceStringNames);

finalization
  dxResourceStringsRepository.UnRegisterProduct('Custom Resource Strings');

end.
