//Flexcel Centralized Configuration file
//Modify the defines in this file to fit your needs.

//Define your language by deleting the "." in the language you want to use.
//If you don't define one, english will be used
{.$DEFINE SPANISH}
{.$DEFINE FRENCH}
{.$DEFINE ITALIAN}
{.$DEFINE ROMANIAN}
{.$DEFINE PORTUGUESEBR}
{.$DEFINE CHINESE}
{.$DEFINE RUSSIAN}
{.$DEFINE GERMAN}
{.$DEFINE POLISH}
{.$DEFINE FINNISH}



//Comment /uncomment the $DEFINE FLEXCELADVSTRINGGRID for TMS AdvStringGrid support.
//Note that you need to install AdvStringGrid for this to work.
//This option is not enabled by default.
{$DEFINE FLEXCELADVSTRINGGRID}
