  ErrNoAdapter='There is no Adapter linked to the report';
  ErrTooManySheets='Tried to insert more sheets than the maximum allowed';

  ErrNoDataSet='Can´t find the dataset %s';
  ErrNoPropDefined='Property "%s" has not been defined or is not published';
  ErrBadProp='Error trying to retrieve property "%s". Verify it is a variant';
  ErrTooManyDimensions='The property "%s" has only %d dimensions';
  ErrIndexOutBounds='The index "%d" of the property "%s" is not in the range %d-%d';

  ErrInvalidDrawingType='Drawing type "%s" invalid';

  ErrNoOpenFile='There is no open file';
  ErrCantFindFile='Can''t find the file "%s"';

  ErrNoTemplate='Error: %s '#13#10'Verify that the active project ("%s") is the correct project';

  ErrDocumentNotSaved='Document was not saved';

  ErrFieldNil='Nil field';
  ErrDupField='Duplicated Field Name: "%s"';
  ErrFieldNotFound='Field not found: "%s"';
  ErrInvalidColumnCount='Invalid column count';

  MsgAbout='FlexCel Studio %s  Get latest version at http://www.tmssoftware.com';

  TxtDatasets='Datasets';
  TxtProperties='Properties';
  TxtExtras=' Extras'; //extra space so it's sorted first

  TxtFileModified='File %s was modified. Do you want to save it?';
  TxtFileModifiedCaption='Warning';
  TxtEditing='Editing %s';
  TxtEditTemplate='Edit Template: %s';
  TxtRefreshTemplate='Select the folder where the original files are';
  TxtTemplateStoreRefreshed='The Template Store has been refreshed';

  TxtDeleteRange='Delete range "%s"?';
  TxtDeleteRangeCaption='Confirm';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Component "%s" does not supports interface IXlsDataSet';
  ErrUseFasterAdapter='This component does not support OLE adapter';

  TxtTrue='TRUE';
  TxtFalse='FALSE';

  ErrInvalidWmf='Wmf file is invalid';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Checking report %s with template %s...';
  TxtError='Error: ';
  TxtOK='OK';
  ErrInvalidRangeName='Error: Invalid Range name: %s';
  ErrRangeNameNotFound='Error: Dataset "%s" for Range name "%s" not found';
  ErrRangeNameInvalidType='Error: Component "%s" for Range name "%s" is not valid for this kind of FlexCelReport';

  ErrCheckCellDots='Cell at Row %d, Column %d, Sheet %d with value "%s" has a "..." character that is not 3 dots ("." "." ".").';
  ErrCheckDotCommandsCol='Cell at Row %d, Column %d, Sheet %d with value "%s" is not on first column';
  ErrInvalidCellDB='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to a non existing dataset.';
  ErrInvalidCellDB2='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid dataset.';
  ErrInvalidField='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid field.';
  ErrInvalidPagesField='PagesDatasetField "%s" is not an existing field of PagesDataSet "%s"';
  ErrFieldOutsideRange='Cell at Row %d, Column %d, Sheet %d with value "%s" is not included in any named range';

  ErrInvalidImageDB='Image at Sheet %d named "%s" refers to an invalid dataset.';
  ErrInvalidImageField='Image at Sheet %d named "%s" refers to an invalid field.';
  ErrInvalidImageType='Image at Sheet %d named "%s" has an invalid ImageType (%s).';

  ErrTemplateNotRefreshed='You should refresh the TemplateStore "%s"''s files because they are older than the ones on the disk.';

  ErrNoAdvStrGrid='There is no AdvStringGrid assigned to this component';
  ErrInvalidSheetName='Invalid sheet name: "%s"';

  ErrInvalidNameForARange='Invalid named range: "%s"';

